# Workflows are defined in special files in the .github/workflows directory, named main.yml
# Workflows can execute based on your chosen event. For this lab, we'll be using the push event.

name: A workflow for my Hello World file
on: push
